// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulszryojvedvkwrezokc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsc3pyeW9qdmVkdmt3cmV6b2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzU1NzEsImV4cCI6MjA2NDgxMTU3MX0.HmwD2vF4ARXZ28bghVxfHKwTwLoz8_nUxj2InUjYUj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);